### ISSUE TITLE
script.py ValueError

### ISSUE THREAD

**Issue by cbenitez101** [ondrakrat/js-mitm-proxy#1]
While invokin the proxy like in the example: **mitmdump -p 8888 -s script.py**
I get the **ValueError("Script name must be provided as the first parameter")** throwed on 7th line of the script.
What am I doing wrong? What else should I pass to de script?
Thanks in advance!

**Comment by ondrakrat** [comment]
Hello, I reckon you're using the `inject_script.py` script, which injects a js into any webpage visited through the proxy. You need to pass the location of the _JS_ script as an argument to the _python_ script, which is done in the following way in mitmproxy:
`mitmdump -p 8888 -s "src/inject_script.py src/js/alert.js"`
If you are using a python script that takes no arguments (such as `modify_headers.py`), you can omit the   quotes as well as the parameter (`mitmdump -p 8888 -s src/modify_headers.py`). Thank you for your comment, I will add this info to the readme.
